### PR TITLE
Chore/update footer

### PR DESCRIPTION
**Pull request by Alperdec**
Problem
=======
What problem or issue does this pull request solve [Jira](https://cruzhacks-dev.atlassian.net/browse/C2D-179)

Solution
========
I added the 2021 icon to footer component and it's corresponding link to cruzhacks2021 website

Change Summary:
---------------
* Tidy, well formulated commit message
* Another great commit message
* Something else I/we did

Dev-Ops
=======
If you added an ENV variable, please check off that you've updated the following  
- [ ] Key & Sample value to `.env` & `sample.env` 
- [ ] GCP Secret Manager (Both development and production)
- [ ] Github Secrets (Added a development and production variable)
- [ ] Github Workflows `.github/workflows/dev.yml` & `.github/workflows/prod.yml`
- [ ] webpack-config.js

Images/Important Notes (optional):
-----------------------
* Insert any notes/issues, dependencies added or removed, or images

### CODE REVIEW

**Review by krishnakpandian — COMMENTED** [review]
I don't know how to describe it but something about the design feels a little bit from the Figma. I think it's because the icon has a heavy highlight even without hover and I think that might be an issue with the icon itself. If you can, let's try updating the svg otherwise let me check with design to see if we can reduce the highlight.

**Comment by Alperdec** [comment]
@krishnakpandian I noticed it too, it looks a little wonky. I attempted to edit the SVG but I'm not sure what to do without making major changes like removing the background from it

**Comment by Alperdec** [comment]
@krishnakpandian I could try to remove the css highlighting all-together from the icons but I have a feeling that the other icons will look dull in comparison to the 2021

**Comment by krishnakpandian** [comment]
@Alperdec Yeah I agree with not removing it everywhere, I'll see if I can get an icon from design that has less highlighting, but otherwise it looks good.

**Review by krishnakpandian — APPROVED** [review]
The glow looks a lot better!

**Pull request merged**
