### PR TITLE
Adding second marketing challenge

### PR DESCRIPTION
**Pull request by krishnakpandian**
Problem
=======
[C2D-181](https://cruzhacks-dev.atlassian.net/browse/C2D-181)

Solution
========
What I/we did to solve this problem
* Added PuzzleModal to milestones component
* Updated props to include a check if a Modal Should exists

Change Summary:
---------------
* Updated Milestones component
* Updated MilestonesProps interface
* Updated Milestones Props

Dev-Ops
=======
If you added an ENV variable, please check off that you've updated the following  
- [ ] Key & Sample value to `.env` & `sample.env` 
- [ ] GCP Secret Manager (Both development and production)
- [ ] Github Secrets (Added a development and production variable)
- [ ] Github Workflows `.github/workflows/dev.yml` & `.github/workflows/prod.yml`
- [ ] webpack-config.js

Images/Important Notes (optional):
-----------------------
* Insert any notes/issues, dependencies added or removed, or images

### CODE REVIEW

**Review by Alperdec — APPROVED** [review]
overall looks good, however I need to go back into puzzle modal and fix the formatting/box sizing. Likely modifying the gap between the question and the input box will fix this or increasing the padding around the text
Screen Shot 2022-01-07 at 10 48 56 PM

**Review by Alperdec — CHANGES_REQUESTED** [review]
comment above

**Comment by krishnakpandian** [comment]
> overall looks good, however I need to go back into puzzle modal and fix the formatting/box sizing. Likely modifying the gap between the question and the input box will fix this or increasing the padding around the text Screen Shot 2022-01-07 at 10 48 56 PM

Good catch! Just curious, but what screen size are you using for this photo?

**Comment by Alperdec** [comment]
@krishnakpandian to be honest I'm not sure what the exact resolution is on my macbook but it was the default display

**Comment by krishnakpandian** [comment]
@Alperdec Ah okay, thanks for checking that out. Last question since I haven't been able to find the dimensions for this UI disparity but were you on safari by any chance?

**Comment by Alperdec** [comment]
@krishnakpandian I was on chrome. I went into responsive dimensions and it seems to reproduce the UI issue after 1000px width. Are you unable to recreate it?

**Comment by krishnakpandian** [comment]
@Alperdec That's so odd, this is what my chrome emulator is showing me for at 1000px. 

krishna-chrome-fill-in-UI

One other thing, we can do test how it would look on deployment. Inside your project folder, run `yarn build` then `firebase use default` and then lastly `firebase emulators:start` to see if there is still a difference. When I ran it on my machine it seems fine, but if it is still clipping, would you like to tackle fixing the UI for this since you are able to reproduce the error.

**Comment by Alperdec** [comment]
@krishnakpandian I'll go ahead and try that out. To be clear though have you tried checking out the issue while giving a wrong answer? It only seems to happen when the error message is returned

**Comment by krishnakpandian** [comment]
> @krishnakpandian I'll go ahead and try that out. To be clear though have you tried checking out the issue while giving a wrong answer? It only seems to happen when the error message is returned

Ah that makes much more sense. Thanks for the sanity check!

**Comment by Alperdec** [comment]
> > @krishnakpandian I'll go ahead and try that out. To be clear though have you tried checking out the issue while giving a wrong answer? It only seems to happen when the error message is returned
> 
> Ah that makes much more sense. Thanks for the sanity check!

No problem hahaha!

**Comment by Alperdec** [comment]
I made some slight adjustments as well. LMK what you think and we can approve this branch and merge it in!

**Comment by krishnakpandian** [comment]
@Alperdec I like the additional CSS changes. Seems like it makes the height spacing cleaner!

**Comment by Alperdec** [comment]
@krishnakpandian Great! I'll go ahead and approve the PR and you can merge when ready

**Review by Alperdec — APPROVED** [review]

**Pull request merged**
